version: '3.1'

services: 
  mongo: 
    image: mongo
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
      MONGO_INITDB_DATABASE: my-db
    ports: # not need when connect from outside 
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


  mongo-express:
     image: mongo-express
     restart: unless-stopped
     ports: 
       - 8081:8081
     environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: root
       ME_CONFIG_MONGODB_ADMINPASSWORD: rootpw
       ME_CONFIG_MONGODB_URL: mongodb://root:rootpw@mongo:27017

