version: '3'
services:
  db:
    image: mysql
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root256
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user256
      - MYSQL_DATABASE=my_db
    #volumes: 
     # - ./db:/var/lib/mysql


